config/routes.rb
Rails.application.routes.draw do
  
  resources :administradors
  resources :statuses
  resources :leituras
  resources :usuarios
  resources :tipo_sensors
  resources :sensors
  
  resources :clientes do
    resources :sensors do
      resources :statuses
      resources :leituras
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'home#index'
  get 'home', to: 'home#index'
  get 'sms', to: 'sms#index'
  get '/clientes/:id_cliente/sensors/:id_sensor/ultima_leitura', to: 'leituras#ul'
  get 'administrators', to: 'administrators#index'
  get '/login', to: 'login#index'
  post '/login', to: 'login#logar'
  get '/sair', to: 'login#deslogar'

end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: %i[ show edit update destroy ]
  before_action :set_sensor
  protect_from_forgery with: :exception  
  protect_from_forgery unless: -> { request.format.json? }  

  # GET /statuses or /statuses.json
  def index
    @statuses = Status.all
    if @sensor == Sensor.all      
      @statuses = Status.all
    else 
      @statuses = Status.where(sensor_id: @sensor.id)
    end
  end

  # GET /statuses/1 or /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses or /statuses.json
  def create
    @status = Status.new(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: "Status was successfully created." }
        format.json { render :show, status: :created, location: @status }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1 or /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: "Status was successfully updated." }
        format.json { render :show, status: :ok, location: @status }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1 or /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url, notice: "Status was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def status_params
      params.require(:status).permit(:flag, :flag_rearme, :flag_mantec, :sensor_id, :cliente_id, :tipo_sensor_id, :nome_sensor)
    end

    def set_sensor
      @sensor = Sensor.where(id: params[:sensor_id]).first
      if @sensor.nil?
        @sensor = Sensor.all
      end
    end
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/statuses/_form.html.erb
<%= form_with(model: status) do |form| %>
  <% if status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
        <% status.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :flag %>
    <%= form.number_field :flag %>
  </div>

  <div class="field">
  <%= form.label :flag_rearme %>
  <%= form.number_field :flag_rearme %>
  </div>

  <div class="field">
  <%= form.label :flag_mantec %>
  <%= form.number_field :flag_mantec %>
  </div>

  <div class="field">
    <%= form.label :sensor_id %>
    <%= form.text_field :sensor_id %>
    <!-- <%= form.select :sensor_id, Sensor.all.collect {|s| [s.nome_sensor, s.id]}, include_blank: true %> -->
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<h1>Editing Status</h1>

<%= render 'form', status: @status %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Statuses</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Flag_notificação</th>
      <th>Flag_rearme</th>
      <th>Flag_mantec</th>
      <th>Sensor ID</th>
      <th>Nome do Sensor</th>
      <th>Cliente</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @statuses.each do |status| %>
      <tr>
        <td><%= status.id %></td>
        <td><%= status.flag %></td>
        <td><%= status.flag_rearme %></td>
        <td><%= status.flag_mantec %></td>
        <td><%= status.sensor_id %></td>
        <td><%= status.sensor.nome_sensor %></td>
        <td><%= status.sensor.cliente.nome_empresa %></td>
        <td><%= link_to 'Show', status %></td>
        <td><%= link_to 'Edit', edit_status_path(status) %></td>
        <td><%= link_to 'Destroy', status, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Status', new_status_path %>

app/views/statuses/new.html.erb
<h1>New Status</h1>

<%= render 'form', status: @status %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Flag_notificação:</strong>
  <%= @status.flag %>
</p>

<p>
  <strong>Flag_rearme:</strong>
  <%= @status.flag_rearme %>
</p>

<p>
  <strong>Flag_rearme:</strong>
  <%= @status.flag_mantec %>
</p>

<p>
  <strong>Sensor:</strong>
  <%= @status.sensor_id %>
</p>

<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>