config/routes.rb
Rails.application.routes.draw do
  
  resources :administradors
  resources :statuses
  resources :leituras
  resources :usuarios
  resources :tipo_sensors
  resources :sensors
  
  resources :clientes do
    resources :sensors do
      resources :statuses
      resources :leituras
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'home#index'
  get 'home', to: 'home#index'
  get 'sms', to: 'sms#index'
  get '/clientes/:id_cliente/sensors/:id_sensor/ultima_leitura', to: 'leituras#ul'
  get 'administrators', to: 'administrators#index'
  get '/login', to: 'login#index'
  post '/login', to: 'login#logar'
  get '/sair', to: 'login#deslogar'

end

app/models/administrador.rb
class Administrador < ApplicationRecord
    validates :nome, :email, :cpf, :senha, presence: true
end

app/controllers/administradors_controller.rb
class AdministradorsController < ApplicationController
  before_action :set_administrador, only: %i[ show edit update destroy ]

  # GET /administradors or /administradors.json
  def index
    @administradors = Administrador.all
  end

  # GET /administradors/1 or /administradors/1.json
  def show
  end

  # GET /administradors/new
  def new
    @administrador = Administrador.new
  end

  # GET /administradors/1/edit
  def edit
  end

  # POST /administradors or /administradors.json
  def create
    @administrador = Administrador.new(administrador_params)

    respond_to do |format|
      if @administrador.save
        format.html { redirect_to administrador_url(@administrador), notice: "Administrador was successfully created." }
        format.json { render :show, status: :created, location: @administrador }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @administrador.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /administradors/1 or /administradors/1.json
  def update
    respond_to do |format|
      if @administrador.update(administrador_params)
        format.html { redirect_to administrador_url(@administrador), notice: "Administrador was successfully updated." }
        format.json { render :show, status: :ok, location: @administrador }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @administrador.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /administradors/1 or /administradors/1.json
  def destroy
    @administrador.destroy

    respond_to do |format|
      format.html { redirect_to administradors_url, notice: "Administrador was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_administrador
      @administrador = Administrador.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def administrador_params
      params.require(:administrador).permit(:nome, :email, :cpf, :senha)
    end
end

app/helpers/administradors_helper.rb
module AdministradorsHelper
end

app/views/administradors/_form.html.erb
<%= form_with(model: administrador) do |form| %>
  <% if administrador.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(administrador.errors.count, "error") %> prohibited this administrador from being saved:</h2>

      <ul>
        <% administrador.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :cpf %>
    <%= form.text_field :cpf %>
  </div>

  <div class="field">
    <%= form.label :senha %>
    <%= form.text_field :senha %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/administradors/edit.html.erb
<h1>Editing Administrador</h1>

<%= render 'form', administrador: @administrador %>

<%= link_to 'Show', @administrador %> |
<%= link_to 'Back', administradors_path %>

app/views/administradors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Administradors</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Email</th>
      <th>Cpf</th>
      <th>Senha</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @administradors.each do |administrador| %>
      <tr>
        <td><%= administrador.nome %></td>
        <td><%= administrador.email %></td>
        <td><%= administrador.cpf %></td>
        <td><%= administrador.senha %></td>
        <td><%= link_to 'Show', administrador %></td>
        <td><%= link_to 'Edit', edit_administrador_path(administrador) %></td>
        <td><%= link_to 'Destroy', administrador, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Administrador', new_administrador_path %>

app/views/administradors/new.html.erb
<h1>New Administrador</h1>

<%= render 'form', administrador: @administrador %>

<%= link_to 'Back', administradors_path %>

app/views/administradors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @administrador.nome %>
</p>

<p>
  <strong>Email:</strong>
  <%= @administrador.email %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @administrador.cpf %>
</p>

<p>
  <strong>Senha:</strong>
  <%= @administrador.senha %>
</p>

<%= link_to 'Edit', edit_administrador_path(@administrador) %> |
<%= link_to 'Back', administradors_path %>