config/routes.rb
Rails.application.routes.draw do
  
  resources :administradors
  resources :statuses
  resources :leituras
  resources :usuarios
  resources :tipo_sensors
  resources :sensors
  
  resources :clientes do
    resources :sensors do
      resources :statuses
      resources :leituras
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'home#index'
  get 'home', to: 'home#index'
  get 'sms', to: 'sms#index'
  get '/clientes/:id_cliente/sensors/:id_sensor/ultima_leitura', to: 'leituras#ul'
  get 'administrators', to: 'administrators#index'
  get '/login', to: 'login#index'
  post '/login', to: 'login#logar'
  get '/sair', to: 'login#deslogar'

end

app/models/sensor.rb
class Sensor < ApplicationRecord
  belongs_to :cliente
  belongs_to :tipo_sensor
  has_many :leituras
  has_many :statuses
end

app/controllers/sensors_controller.rb
class SensorsController < ApplicationController
  before_action :set_sensor, only: %i[ show edit update destroy]
  before_action :set_cliente
  skip_before_action :verify_authenticity_token
  skip_before_action :authenticate_user!

  # GET /sensors or /sensors.json
  def index
    releaseCrossDomain
    if @cliente == Cliente.all
      @sensors = Sensor.all
    else
      @sensors = Sensor.where(cliente_id: @cliente.id)
    end
  end

  # GET /sensors/1 or /sensors/1.json
  def show
  end

  # GET /sensors/new
  def new
    @sensor = Sensor.new
  end

  # GET /sensors/1/edit
  def edit
  end

  # POST /sensors or /sensors.json
  def create
    @sensor = Sensor.new(sensor_params)
    
    respond_to do |format|
      if @sensor.save
        format.html { redirect_to cliente_sensors_path(@cliente), notice: "Sensor was successfully created." }
        format.json { render :show, status: :created, location: @sensor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sensor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sensors/1 or /sensors/1.json
  def update
    respond_to do |format|
      if @sensor.update(sensor_params)
        format.html { redirect_to cliente_sensors_path(@cliente), notice: "Sensor was successfully updated." }
        format.json { render :show, status: :ok, location: @sensor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sensor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sensors/1 or /sensors/1.json
  def destroy
    @sensor.destroy
    respond_to do |format|
      format.html { redirect_to cliente_sensors_path(@cliente), notice: "Sensor was successfully destroyed." }
      format.json { head :no_content }
    end
  end




  private
    # Use callbacks to share common setup or constraints between actions.
    
    def set_cliente
      @cliente = Cliente.where(id: params[:cliente_id]).first
      if @cliente.nil?
        @cliente = Cliente.all
      end
    end
    
    def set_sensor
      @sensor = Sensor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sensor_params
      params.require(:sensor).permit(:nome_sensor, :Li, :Ls, :cliente_id, :tipo_sensor_id, :time_read)
    end

    def releaseCrossDomain

      origin = request.headers["Origin"]
  
      if (not origin.nil?) and (origin == "https://ib.ampmsolucoes.com.br" or origin == "https://api.ampmsolucoes.com.br" or origin == "192.168.15.10")
        origin = origin
        else
          origin = ""
      end
      
      headers['Access-Control-Allow-Origin'] = '*'
      headers['Access-Control-Allow-Methods'] = 'GET, POST'
      headers['Access-Control-Request-Method'] = '*'
      headers['Access-Control-Allow-Headers'] = '*'
    end

end

app/helpers/sensors_helper.rb
module SensorsHelper
end

app/views/sensors/_form.html.erb
<%= form_with(model: [@cliente_id, @sensor]) do |form| %>
  <% if sensor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sensor.errors.count, "error") %> prohibited this sensor from being saved:</h2>

      <ul>
        <% sensor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome_sensor %>
    <%= form.text_field :nome_sensor %>
  </div>

  <div class="field">
  <%= form.label :LI %>
  <%= form.text_field :Li %>
</div>

<div class="field">
<%= form.label :LS %>
<%= form.text_field :Ls %>
</div>

<div class="field">
  <%= form.label :cliente_id %>
  <!-- <%= form.text_field :cliente_id %> -->
  <%= form.select :cliente_id, Cliente.all.collect {|c| [c.nome_empresa, c.id]}, include_blank: true %>

</div>

<div class="field">
  <%= form.label :tipo_sensor_id %>
  <!-- <%= form.text_field :tipo_sensor_id %> -->
  <%= form.select :tipo_sensor_id, TipoSensor.all.collect {|t| [t.tipo_sensor, t.id]}, include_blank: true %>
</div>

<div class="field">
<%= form.label :Time_read %>
<%= form.text_field :time_read %>
</div>

<div class="actions">
  <%= form.submit %>
</div>
<% end %>

app/views/sensors/edit.html.erb
<h1>Editing Sensor</h1>

<%= render 'form', sensor: @sensor %>

<%= link_to 'Show', @sensor %> |
<%= link_to 'Back', sensors_path %>

app/views/sensors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sensors</h1>

<table>
  <thead>
    <tr>
      <th>ID Sensor</th>
      <th>Nome sensor</th>
      <th>LI</th>
      <th>LS</th>
      <th>Cliente</th>
      <th>Tipo sensor</th>
      <th>Time read</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sensors.each do |sensor| %>
      <tr>
        <td><%= sensor.id %></td>
        <td><%= sensor.nome_sensor %></td>
        <td><%= sensor.Li %></td>
        <td><%= sensor.Ls %></td>
        <td><%= sensor.cliente.nome_empresa %></td>
        <td><%= sensor.tipo_sensor.tipo_sensor %></td>
        <td><%= sensor.time_read %></td>
        <td><%= link_to 'Leituras', cliente_sensor_leituras_path(@cliente, sensor) %></td>
        <td><%= link_to 'Status Flags', cliente_sensor_statuses_path(@cliente, sensor) %></td>
        <td><%= link_to 'Show', cliente_sensor_path(@cliente, sensor) %></td>
        <td><%= link_to 'Edit', edit_cliente_sensor_path(@cliente, sensor) %></td>
        <td><%= link_to 'Destroy', cliente_sensor_path(@cliente, sensor), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sensor', new_cliente_sensor_path(@cliente) %>

app/views/sensors/new.html.erb
<h1>New Sensor</h1>

<%= render 'form', sensor: @sensor %>

<%= link_to 'Back', cliente_sensors_path(@cliente) %>

app/views/sensors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome sensor:</strong>
  <%= @sensor.nome_sensor %>
</p>

<p>
  <strong>LI:</strong>
  <%= @sensor.Li %>
</p>

<p>
  <strong>LS</strong>
  <%= @sensor.Ls %>
</p>

<p>
  <strong>Cliente:</strong>
  <%= @sensor.cliente.nome_empresa%>
</p>

<p>
  <strong>Tipo sensor:</strong>
  <%= @sensor.tipo_sensor.tipo_sensor %>
</p>

<p>
  <strong>Time Read</strong>
  <%= @sensor.time_read %>
</p>

<%= link_to 'Edit', edit_cliente_sensor_path(@cliente, @sensor) %> |
<%= link_to 'Back', cliente_sensors_path(@cliente) %>